/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as AuthedCategoriesRouteImport } from './routes/_authed/categories'
import { Route as AuthedConnectionsRouteImport } from './routes/_authed/connections'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedInboxRouteImport } from './routes/_authed/inbox'
import { Route as AuthedNetWorthRouteImport } from './routes/_authed/net-worth'
import { Route as AuthedPennyRouteImport } from './routes/_authed/penny'
import { Route as AuthedRecurringRouteImport } from './routes/_authed/recurring'
import { Route as AuthedRegisterRouteImport } from './routes/_authed/register'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as ConnectOauthReturnRouteImport } from './routes/connect.oauth-return'
import { Route as AuthedAccountsDebtRouteImport } from './routes/_authed/accounts_.debt'
import { Route as AuthedCategoriesIndexRouteImport } from './routes/_authed/categories.index'
import { Route as AuthedCategoriesLearningRouteImport } from './routes/_authed/categories.learning'
import { Route as AuthedCategoriesRulesRouteImport } from './routes/_authed/categories.rules'
import { Route as AuthedCategoriesTagsRouteImport } from './routes/_authed/categories.tags'
import { Route as AuthedPennyConversationIdRouteImport } from './routes/_authed/penny_.$conversationId'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings.index'
import { Route as AuthedSettingsDeveloperRouteImport } from './routes/_authed/settings.developer'
import { Route as AuthedSettingsPreferencesRouteImport } from './routes/_authed/settings.preferences'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed/settings.security'
import { Route as AuthedAccountsDebtAddRouteImport } from './routes/_authed/accounts_.debt.add'
import { Route as AuthedAccountsDebtAccountIdRouteImport } from './routes/_authed/accounts_.debt_.$accountId'
import { Route as AuthedAccountsInvestmentsAccountIdRouteImport } from './routes/_authed/accounts_.investments_.$accountId'
import { Route as AuthedCategoriesRulesIndexRouteImport } from './routes/_authed/categories.rules.index'
import { Route as AuthedCategoriesRulesRuleIdRouteImport } from './routes/_authed/categories.rules.$ruleId'
import { Route as AuthedCategoriesRulesNewRouteImport } from './routes/_authed/categories.rules.new'
import { Route as AuthedAccountsDebtAccountIdTermsRouteImport } from './routes/_authed/accounts_.debt_.$accountId.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesRoute = AuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsRoute = AuthedConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInboxRoute = AuthedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetWorthRoute = AuthedNetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPennyRoute = AuthedPennyRouteImport.update({
  id: '/penny',
  path: '/penny',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecurringRoute = AuthedRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRegisterRoute = AuthedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const ConnectOauthReturnRoute = ConnectOauthReturnRouteImport.update({
  id: '/connect/oauth-return',
  path: '/connect/oauth-return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountsDebtRoute = AuthedAccountsDebtRouteImport.update({
  id: '/accounts_/debt',
  path: '/accounts/debt',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesIndexRoute = AuthedCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCategoriesRoute,
} as any)
const AuthedCategoriesLearningRoute =
  AuthedCategoriesLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthedCategoriesRoute,
  } as any)
const AuthedCategoriesRulesRoute = AuthedCategoriesRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthedCategoriesRoute,
} as any)
const AuthedCategoriesTagsRoute = AuthedCategoriesTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthedCategoriesRoute,
} as any)
const AuthedPennyConversationIdRoute =
  AuthedPennyConversationIdRouteImport.update({
    id: '/penny_/$conversationId',
    path: '/penny/$conversationId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsDeveloperRoute = AuthedSettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsPreferencesRoute =
  AuthedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedAccountsDebtAddRoute = AuthedAccountsDebtAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthedAccountsDebtRoute,
} as any)
const AuthedAccountsDebtAccountIdRoute =
  AuthedAccountsDebtAccountIdRouteImport.update({
    id: '/accounts_/debt_/$accountId',
    path: '/accounts/debt/$accountId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAccountsInvestmentsAccountIdRoute =
  AuthedAccountsInvestmentsAccountIdRouteImport.update({
    id: '/accounts_/investments_/$accountId',
    path: '/accounts/investments/$accountId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCategoriesRulesIndexRoute =
  AuthedCategoriesRulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCategoriesRulesRoute,
  } as any)
const AuthedCategoriesRulesRuleIdRoute =
  AuthedCategoriesRulesRuleIdRouteImport.update({
    id: '/$ruleId',
    path: '/$ruleId',
    getParentRoute: () => AuthedCategoriesRulesRoute,
  } as any)
const AuthedCategoriesRulesNewRoute =
  AuthedCategoriesRulesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCategoriesRulesRoute,
  } as any)
const AuthedAccountsDebtAccountIdTermsRoute =
  AuthedAccountsDebtAccountIdTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => AuthedAccountsDebtAccountIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounts': typeof AuthedAccountsRoute
  '/categories': typeof AuthedCategoriesRouteWithChildren
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inbox': typeof AuthedInboxRoute
  '/net-worth': typeof AuthedNetWorthRoute
  '/penny': typeof AuthedPennyRoute
  '/recurring': typeof AuthedRecurringRoute
  '/register': typeof AuthedRegisterRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/connect/oauth-return': typeof ConnectOauthReturnRoute
  '/accounts/debt': typeof AuthedAccountsDebtRouteWithChildren
  '/categories/learning': typeof AuthedCategoriesLearningRoute
  '/categories/rules': typeof AuthedCategoriesRulesRouteWithChildren
  '/categories/tags': typeof AuthedCategoriesTagsRoute
  '/penny/$conversationId': typeof AuthedPennyConversationIdRoute
  '/settings/developer': typeof AuthedSettingsDeveloperRoute
  '/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/categories/': typeof AuthedCategoriesIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/accounts/debt/add': typeof AuthedAccountsDebtAddRoute
  '/accounts/debt/$accountId': typeof AuthedAccountsDebtAccountIdRouteWithChildren
  '/accounts/investments/$accountId': typeof AuthedAccountsInvestmentsAccountIdRoute
  '/categories/rules/$ruleId': typeof AuthedCategoriesRulesRuleIdRoute
  '/categories/rules/new': typeof AuthedCategoriesRulesNewRoute
  '/categories/rules/': typeof AuthedCategoriesRulesIndexRoute
  '/accounts/debt/$accountId/terms': typeof AuthedAccountsDebtAccountIdTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounts': typeof AuthedAccountsRoute
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inbox': typeof AuthedInboxRoute
  '/net-worth': typeof AuthedNetWorthRoute
  '/penny': typeof AuthedPennyRoute
  '/recurring': typeof AuthedRecurringRoute
  '/register': typeof AuthedRegisterRoute
  '/connect/oauth-return': typeof ConnectOauthReturnRoute
  '/accounts/debt': typeof AuthedAccountsDebtRouteWithChildren
  '/categories/learning': typeof AuthedCategoriesLearningRoute
  '/categories/tags': typeof AuthedCategoriesTagsRoute
  '/penny/$conversationId': typeof AuthedPennyConversationIdRoute
  '/settings/developer': typeof AuthedSettingsDeveloperRoute
  '/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/categories': typeof AuthedCategoriesIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/accounts/debt/add': typeof AuthedAccountsDebtAddRoute
  '/accounts/debt/$accountId': typeof AuthedAccountsDebtAccountIdRouteWithChildren
  '/accounts/investments/$accountId': typeof AuthedAccountsInvestmentsAccountIdRoute
  '/categories/rules/$ruleId': typeof AuthedCategoriesRulesRuleIdRoute
  '/categories/rules/new': typeof AuthedCategoriesRulesNewRoute
  '/categories/rules': typeof AuthedCategoriesRulesIndexRoute
  '/accounts/debt/$accountId/terms': typeof AuthedAccountsDebtAccountIdTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/categories': typeof AuthedCategoriesRouteWithChildren
  '/_authed/connections': typeof AuthedConnectionsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/inbox': typeof AuthedInboxRoute
  '/_authed/net-worth': typeof AuthedNetWorthRoute
  '/_authed/penny': typeof AuthedPennyRoute
  '/_authed/recurring': typeof AuthedRecurringRoute
  '/_authed/register': typeof AuthedRegisterRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/connect/oauth-return': typeof ConnectOauthReturnRoute
  '/_authed/accounts_/debt': typeof AuthedAccountsDebtRouteWithChildren
  '/_authed/categories/learning': typeof AuthedCategoriesLearningRoute
  '/_authed/categories/rules': typeof AuthedCategoriesRulesRouteWithChildren
  '/_authed/categories/tags': typeof AuthedCategoriesTagsRoute
  '/_authed/penny_/$conversationId': typeof AuthedPennyConversationIdRoute
  '/_authed/settings/developer': typeof AuthedSettingsDeveloperRoute
  '/_authed/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRoute
  '/_authed/categories/': typeof AuthedCategoriesIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/accounts_/debt/add': typeof AuthedAccountsDebtAddRoute
  '/_authed/accounts_/debt_/$accountId': typeof AuthedAccountsDebtAccountIdRouteWithChildren
  '/_authed/accounts_/investments_/$accountId': typeof AuthedAccountsInvestmentsAccountIdRoute
  '/_authed/categories/rules/$ruleId': typeof AuthedCategoriesRulesRuleIdRoute
  '/_authed/categories/rules/new': typeof AuthedCategoriesRulesNewRoute
  '/_authed/categories/rules/': typeof AuthedCategoriesRulesIndexRoute
  '/_authed/accounts_/debt_/$accountId/terms': typeof AuthedAccountsDebtAccountIdTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/accounts'
    | '/categories'
    | '/connections'
    | '/dashboard'
    | '/inbox'
    | '/net-worth'
    | '/penny'
    | '/recurring'
    | '/register'
    | '/settings'
    | '/connect/oauth-return'
    | '/accounts/debt'
    | '/categories/learning'
    | '/categories/rules'
    | '/categories/tags'
    | '/penny/$conversationId'
    | '/settings/developer'
    | '/settings/preferences'
    | '/settings/security'
    | '/categories/'
    | '/settings/'
    | '/accounts/debt/add'
    | '/accounts/debt/$accountId'
    | '/accounts/investments/$accountId'
    | '/categories/rules/$ruleId'
    | '/categories/rules/new'
    | '/categories/rules/'
    | '/accounts/debt/$accountId/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/accounts'
    | '/connections'
    | '/dashboard'
    | '/inbox'
    | '/net-worth'
    | '/penny'
    | '/recurring'
    | '/register'
    | '/connect/oauth-return'
    | '/accounts/debt'
    | '/categories/learning'
    | '/categories/tags'
    | '/penny/$conversationId'
    | '/settings/developer'
    | '/settings/preferences'
    | '/settings/security'
    | '/categories'
    | '/settings'
    | '/accounts/debt/add'
    | '/accounts/debt/$accountId'
    | '/accounts/investments/$accountId'
    | '/categories/rules/$ruleId'
    | '/categories/rules/new'
    | '/categories/rules'
    | '/accounts/debt/$accountId/terms'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authed/accounts'
    | '/_authed/categories'
    | '/_authed/connections'
    | '/_authed/dashboard'
    | '/_authed/inbox'
    | '/_authed/net-worth'
    | '/_authed/penny'
    | '/_authed/recurring'
    | '/_authed/register'
    | '/_authed/settings'
    | '/connect/oauth-return'
    | '/_authed/accounts_/debt'
    | '/_authed/categories/learning'
    | '/_authed/categories/rules'
    | '/_authed/categories/tags'
    | '/_authed/penny_/$conversationId'
    | '/_authed/settings/developer'
    | '/_authed/settings/preferences'
    | '/_authed/settings/security'
    | '/_authed/categories/'
    | '/_authed/settings/'
    | '/_authed/accounts_/debt/add'
    | '/_authed/accounts_/debt_/$accountId'
    | '/_authed/accounts_/investments_/$accountId'
    | '/_authed/categories/rules/$ruleId'
    | '/_authed/categories/rules/new'
    | '/_authed/categories/rules/'
    | '/_authed/accounts_/debt_/$accountId/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ConnectOauthReturnRoute: typeof ConnectOauthReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories': {
      id: '/_authed/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthedCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections': {
      id: '/_authed/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthedConnectionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/net-worth': {
      id: '/_authed/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof AuthedNetWorthRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/penny': {
      id: '/_authed/penny'
      path: '/penny'
      fullPath: '/penny'
      preLoaderRoute: typeof AuthedPennyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recurring': {
      id: '/_authed/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AuthedRecurringRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/register': {
      id: '/_authed/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthedRegisterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/connect/oauth-return': {
      id: '/connect/oauth-return'
      path: '/connect/oauth-return'
      fullPath: '/connect/oauth-return'
      preLoaderRoute: typeof ConnectOauthReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accounts_/debt': {
      id: '/_authed/accounts_/debt'
      path: '/accounts/debt'
      fullPath: '/accounts/debt'
      preLoaderRoute: typeof AuthedAccountsDebtRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories/': {
      id: '/_authed/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthedCategoriesIndexRouteImport
      parentRoute: typeof AuthedCategoriesRoute
    }
    '/_authed/categories/learning': {
      id: '/_authed/categories/learning'
      path: '/learning'
      fullPath: '/categories/learning'
      preLoaderRoute: typeof AuthedCategoriesLearningRouteImport
      parentRoute: typeof AuthedCategoriesRoute
    }
    '/_authed/categories/rules': {
      id: '/_authed/categories/rules'
      path: '/rules'
      fullPath: '/categories/rules'
      preLoaderRoute: typeof AuthedCategoriesRulesRouteImport
      parentRoute: typeof AuthedCategoriesRoute
    }
    '/_authed/categories/tags': {
      id: '/_authed/categories/tags'
      path: '/tags'
      fullPath: '/categories/tags'
      preLoaderRoute: typeof AuthedCategoriesTagsRouteImport
      parentRoute: typeof AuthedCategoriesRoute
    }
    '/_authed/penny_/$conversationId': {
      id: '/_authed/penny_/$conversationId'
      path: '/penny/$conversationId'
      fullPath: '/penny/$conversationId'
      preLoaderRoute: typeof AuthedPennyConversationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/developer': {
      id: '/_authed/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof AuthedSettingsDeveloperRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/preferences': {
      id: '/_authed/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthedSettingsPreferencesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/accounts_/debt/add': {
      id: '/_authed/accounts_/debt/add'
      path: '/add'
      fullPath: '/accounts/debt/add'
      preLoaderRoute: typeof AuthedAccountsDebtAddRouteImport
      parentRoute: typeof AuthedAccountsDebtRoute
    }
    '/_authed/accounts_/debt_/$accountId': {
      id: '/_authed/accounts_/debt_/$accountId'
      path: '/accounts/debt/$accountId'
      fullPath: '/accounts/debt/$accountId'
      preLoaderRoute: typeof AuthedAccountsDebtAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts_/investments_/$accountId': {
      id: '/_authed/accounts_/investments_/$accountId'
      path: '/accounts/investments/$accountId'
      fullPath: '/accounts/investments/$accountId'
      preLoaderRoute: typeof AuthedAccountsInvestmentsAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories/rules/': {
      id: '/_authed/categories/rules/'
      path: '/'
      fullPath: '/categories/rules/'
      preLoaderRoute: typeof AuthedCategoriesRulesIndexRouteImport
      parentRoute: typeof AuthedCategoriesRulesRoute
    }
    '/_authed/categories/rules/$ruleId': {
      id: '/_authed/categories/rules/$ruleId'
      path: '/$ruleId'
      fullPath: '/categories/rules/$ruleId'
      preLoaderRoute: typeof AuthedCategoriesRulesRuleIdRouteImport
      parentRoute: typeof AuthedCategoriesRulesRoute
    }
    '/_authed/categories/rules/new': {
      id: '/_authed/categories/rules/new'
      path: '/new'
      fullPath: '/categories/rules/new'
      preLoaderRoute: typeof AuthedCategoriesRulesNewRouteImport
      parentRoute: typeof AuthedCategoriesRulesRoute
    }
    '/_authed/accounts_/debt_/$accountId/terms': {
      id: '/_authed/accounts_/debt_/$accountId/terms'
      path: '/terms'
      fullPath: '/accounts/debt/$accountId/terms'
      preLoaderRoute: typeof AuthedAccountsDebtAccountIdTermsRouteImport
      parentRoute: typeof AuthedAccountsDebtAccountIdRoute
    }
  }
}

interface AuthedCategoriesRulesRouteChildren {
  AuthedCategoriesRulesRuleIdRoute: typeof AuthedCategoriesRulesRuleIdRoute
  AuthedCategoriesRulesNewRoute: typeof AuthedCategoriesRulesNewRoute
  AuthedCategoriesRulesIndexRoute: typeof AuthedCategoriesRulesIndexRoute
}

const AuthedCategoriesRulesRouteChildren: AuthedCategoriesRulesRouteChildren = {
  AuthedCategoriesRulesRuleIdRoute: AuthedCategoriesRulesRuleIdRoute,
  AuthedCategoriesRulesNewRoute: AuthedCategoriesRulesNewRoute,
  AuthedCategoriesRulesIndexRoute: AuthedCategoriesRulesIndexRoute,
}

const AuthedCategoriesRulesRouteWithChildren =
  AuthedCategoriesRulesRoute._addFileChildren(
    AuthedCategoriesRulesRouteChildren,
  )

interface AuthedCategoriesRouteChildren {
  AuthedCategoriesLearningRoute: typeof AuthedCategoriesLearningRoute
  AuthedCategoriesRulesRoute: typeof AuthedCategoriesRulesRouteWithChildren
  AuthedCategoriesTagsRoute: typeof AuthedCategoriesTagsRoute
  AuthedCategoriesIndexRoute: typeof AuthedCategoriesIndexRoute
}

const AuthedCategoriesRouteChildren: AuthedCategoriesRouteChildren = {
  AuthedCategoriesLearningRoute: AuthedCategoriesLearningRoute,
  AuthedCategoriesRulesRoute: AuthedCategoriesRulesRouteWithChildren,
  AuthedCategoriesTagsRoute: AuthedCategoriesTagsRoute,
  AuthedCategoriesIndexRoute: AuthedCategoriesIndexRoute,
}

const AuthedCategoriesRouteWithChildren =
  AuthedCategoriesRoute._addFileChildren(AuthedCategoriesRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsDeveloperRoute: typeof AuthedSettingsDeveloperRoute
  AuthedSettingsPreferencesRoute: typeof AuthedSettingsPreferencesRoute
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsDeveloperRoute: AuthedSettingsDeveloperRoute,
  AuthedSettingsPreferencesRoute: AuthedSettingsPreferencesRoute,
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedAccountsDebtRouteChildren {
  AuthedAccountsDebtAddRoute: typeof AuthedAccountsDebtAddRoute
}

const AuthedAccountsDebtRouteChildren: AuthedAccountsDebtRouteChildren = {
  AuthedAccountsDebtAddRoute: AuthedAccountsDebtAddRoute,
}

const AuthedAccountsDebtRouteWithChildren =
  AuthedAccountsDebtRoute._addFileChildren(AuthedAccountsDebtRouteChildren)

interface AuthedAccountsDebtAccountIdRouteChildren {
  AuthedAccountsDebtAccountIdTermsRoute: typeof AuthedAccountsDebtAccountIdTermsRoute
}

const AuthedAccountsDebtAccountIdRouteChildren: AuthedAccountsDebtAccountIdRouteChildren =
  {
    AuthedAccountsDebtAccountIdTermsRoute:
      AuthedAccountsDebtAccountIdTermsRoute,
  }

const AuthedAccountsDebtAccountIdRouteWithChildren =
  AuthedAccountsDebtAccountIdRoute._addFileChildren(
    AuthedAccountsDebtAccountIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedCategoriesRoute: typeof AuthedCategoriesRouteWithChildren
  AuthedConnectionsRoute: typeof AuthedConnectionsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInboxRoute: typeof AuthedInboxRoute
  AuthedNetWorthRoute: typeof AuthedNetWorthRoute
  AuthedPennyRoute: typeof AuthedPennyRoute
  AuthedRecurringRoute: typeof AuthedRecurringRoute
  AuthedRegisterRoute: typeof AuthedRegisterRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedAccountsDebtRoute: typeof AuthedAccountsDebtRouteWithChildren
  AuthedPennyConversationIdRoute: typeof AuthedPennyConversationIdRoute
  AuthedAccountsDebtAccountIdRoute: typeof AuthedAccountsDebtAccountIdRouteWithChildren
  AuthedAccountsInvestmentsAccountIdRoute: typeof AuthedAccountsInvestmentsAccountIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedCategoriesRoute: AuthedCategoriesRouteWithChildren,
  AuthedConnectionsRoute: AuthedConnectionsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInboxRoute: AuthedInboxRoute,
  AuthedNetWorthRoute: AuthedNetWorthRoute,
  AuthedPennyRoute: AuthedPennyRoute,
  AuthedRecurringRoute: AuthedRecurringRoute,
  AuthedRegisterRoute: AuthedRegisterRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedAccountsDebtRoute: AuthedAccountsDebtRouteWithChildren,
  AuthedPennyConversationIdRoute: AuthedPennyConversationIdRoute,
  AuthedAccountsDebtAccountIdRoute:
    AuthedAccountsDebtAccountIdRouteWithChildren,
  AuthedAccountsInvestmentsAccountIdRoute:
    AuthedAccountsInvestmentsAccountIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ConnectOauthReturnRoute: ConnectOauthReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
